### ISSUE TITLE
Lab 2

### ISSUE THREAD

**Issue by AntonC9018** [chapyyck/ASDC#1]
https://github.com/chapyyck/ASDC/blob/b14c3014c04638c06dfa1c648a296883ef8aaee9/lab_2/WorkWithCSV/CSV.java#L33-L35
Это тупо. Сделать проверку на пустую строку если хочешь поддерживать запятые в конце строки.
```java
if (parts.length() == 4 || parts.length() == 5 && parts[4] == "")
{
    // ...
}
```
Или вот так хотя бы:
```java
int len = parts.length();
if (len == 0)
{
    // error
}

if (parts[len - 1] == "")
{
    len -= 1;
}

if (len != 4)
{
    // error
}
```

Этот код намного проще чем то что у тебя, и он делает гораздо меньше. То что у тебя -- "clever", не стремись к такому.
Для понятности можешь ввести локальную переменную для условия.
Самый простой вариант вообще будет вот так:
```java
boolean hasTrailingComma = line.length() != 0 && line[line.length() - 1] == ',';
int len = parts.length();
if (hasTrailingComma)
{
    len -= 1;
}
if (len != 4)
{
    // error
}
```

https://github.com/chapyyck/ASDC/blob/b14c3014c04638c06dfa1c648a296883ef8aaee9/lab_2/WorkWithCSV/CSV.java#L23
Проверка на запятую тут бессмысленна, потому что ты уже поделил на запятых.

https://github.com/chapyyck/ASDC/blob/b14c3014c04638c06dfa1c648a296883ef8aaee9/lab_2/WorkWithCSV/Person.java#L9
Либо вытащи наружу это, либо переименуй без Person (он так и так уже в Person).

https://github.com/chapyyck/ASDC/blob/b14c3014c04638c06dfa1c648a296883ef8aaee9/lab_2/WorkWithCSV/Main.java#L15-L18
Строку в переменную, раз используешь больше чем 1 раз.

https://github.com/chapyyck/ASDC/blob/b14c3014c04638c06dfa1c648a296883ef8aaee9/lab_2/WorkWithCSV/CSV.java#L13
Поэтому мне не нравятся высокоуровневые языки программирования (как минимум для алгоритмической работы). Java тебя заставляет динамически выделять строку для каждого объекта отдельно, просто чтобы потом вписать ее в консоль. Вероятно есть какая-то менее доступная абстракция, которая позволила бы это сделать без стадии строки. Прошу хотя бы задуматься об этих вещах когда пишешь код -- будет полезно, если собираешься стать сильным программистом.

**Comment by AntonC9018** [comment]
Почему закрыл, раз не пофиксил с подсчетом запятых?
Я думаю у `split` должен быть флаг который позволяет пустые строки в ответе. Поищи в доках.

**Comment by AntonC9018** [comment]
Подсчитай запятые хотя бы по человечески, циклом. Зачем новую строку выделять для этого?

**Comment by AntonC9018** [comment]
https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Time_Analysis/conclusion.md?plain=1#L17
В лучшем случае $` log(N) `$ уровней будет. Используй $` N `$ желательно всегда для количества элементов. Количество уровней переименуй в идеале в $` L `$, или типа того.

https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Time_Analysis/conclusion.md?plain=1#L31
https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Time_Analysis/conclusion.md?plain=1#L36
Почему нет? Сменятся просто проверки с больше на меньше.

https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Time_Analysis/SortedAnalysis.java#L12-L16
https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Time_Analysis/SortedAnalysis.java#L20-L24
https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Time_Analysis/UnsortedAnalysis.java#L11-L15
Один и тот же код повторяется. Используй полиморфизм тут.

https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Time_Analysis/conclusion.md?plain=1#L42
Экспоненциальный еще может работать не имея всего массива заранее.

https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Searching_SortedArr/ExponentialSearch.java#L5-L22
https://github.com/chapyyck/ASDC/blob/511079fc132a85ac89a07aa4b4efec168e83e42e/lab_2/Searching_SortedArr/BinarySearch.java#L4-L24
Зачем здесь код повторяется?

**Comment by chapyyck** [comment]
Надеюсь я когда-то продвинусь дальше третьей лабы 
![boom](https://github.com/chapyyck/ASDC/assets/110742463/e320896d-879e-45c8-a1b6-91062e1b36f4)

**Comment by AntonC9018** [comment]
Пока все хорошо, справляешься
